-- ============================================================================
-- CLEARSET AI — SNOWFLAKE DATABASE & SCHEMA SETUP
-- Domain: Financial Services / Capital Markets / Post-Trade Operations
-- ============================================================================

CREATE DATABASE IF NOT EXISTS CLEARSET_DB;
USE DATABASE CLEARSET_DB;

CREATE SCHEMA IF NOT EXISTS CLEARSET_SCHEMA;
USE SCHEMA CLEARSET_SCHEMA;

-- 1. COUNTERPARTIES MASTER
CREATE OR REPLACE TABLE COUNTERPARTIES (
    CP_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BIC VARCHAR(20) NOT NULL,
    LEI VARCHAR(50),
    CREDIT_RATING VARCHAR(10),
    PRIOR_FAILURES_30D INT DEFAULT 0,
    TOTAL_TRADES_TODAY INT DEFAULT 0,
    HISTORICAL_FAIL_RATE FLOAT DEFAULT 0.0,
    AVG_RESOLUTION_HOURS FLOAT DEFAULT 0.0,
    PRIMARY_DESK_CONTACT VARCHAR(255),
    PRIMARY_EMAIL VARCHAR(255),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. SECURITIES MASTER
CREATE OR REPLACE TABLE SECURITIES (
    ISIN VARCHAR(20) PRIMARY KEY,
    CUSIP VARCHAR(20),
    TICKER VARCHAR(20) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ASSET_CLASS VARCHAR(50) NOT NULL,
    DEPOSITORY VARCHAR(50) NOT NULL,
    MARKET_TIER VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. TRADES
CREATE OR REPLACE TABLE TRADES (
    TRADE_ID VARCHAR(50) PRIMARY KEY,
    ISIN VARCHAR(20) REFERENCES SECURITIES(ISIN),
    CP_ID VARCHAR(50) REFERENCES COUNTERPARTIES(CP_ID),
    TRADE_DATE TIMESTAMP_NTZ NOT NULL,
    SETTLEMENT_DATE DATE NOT NULL,
    SETTLEMENT_TYPE VARCHAR(10) DEFAULT 'DVP',
    TRADE_VALUE NUMBER(18, 2) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE NUMBER(18, 4) NOT NULL,
    CURRENCY VARCHAR(10) DEFAULT 'USD',
    BOOKING_DESK VARCHAR(100),
    TRADER_REF VARCHAR(100),
    SETTLEMENT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    INSTRUCTION_STATUS VARCHAR(50) DEFAULT 'MISSING',
    CUTOFF_TIME TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. SETTLEMENT INSTRUCTIONS (SSI)
CREATE OR REPLACE TABLE SETTLEMENT_INSTRUCTIONS (
    INSTRUCTION_ID VARCHAR(50) PRIMARY KEY,
    TRADE_ID VARCHAR(50) REFERENCES TRADES(TRADE_ID),
    SETTLEMENT_TYPE VARCHAR(10),
    CUSTODIAN_BIC VARCHAR(20),
    DEPOSITORY VARCHAR(50),
    CASH_ACCOUNT VARCHAR(100),
    SECURITIES_ACCOUNT VARCHAR(100),
    STATUS VARCHAR(50) NOT NULL,
    MISMATCH_DETAILS TEXT,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. SETTLEMENT EVENTS (SWIFT / ISO 20022 Audit Trail)
CREATE OR REPLACE TABLE SETTLEMENT_EVENTS (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    TRADE_ID VARCHAR(50) REFERENCES TRADES(TRADE_ID),
    EVENT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MESSAGE_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SOURCE VARCHAR(50) NOT NULL
);

-- 6. EXCEPTIONS & RISK ENGINE LOGS
CREATE OR REPLACE TABLE EXCEPTIONS (
    EXCEPTION_ID VARCHAR(50) PRIMARY KEY,
    TRADE_ID VARCHAR(50) REFERENCES TRADES(TRADE_ID),
    SEVERITY VARCHAR(20) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'OPEN',
    EXCEPTION_TYPE VARCHAR(100) NOT NULL,
    RISK_SCORE INT NOT NULL,
    RISK_BREAKDOWN_JSON VARIANT,
    DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ASSIGNED_ANALYST VARCHAR(100),
    RESOLVED_AT TIMESTAMP_NTZ
);

-- 7. INVESTIGATION CASES & AUDIT TRAIL
CREATE OR REPLACE TABLE INVESTIGATIONS (
    CASE_ID VARCHAR(50) PRIMARY KEY,
    TRADE_ID VARCHAR(50) REFERENCES TRADES(TRADE_ID),
    TRADE_VALUE NUMBER(18, 2),
    RISK_SCORE INT NOT NULL,
    SEVERITY VARCHAR(20),
    ROOT_CAUSE TEXT,
    AI_RECOMMENDATION TEXT,
    HUMAN_DECISION VARCHAR(50),
    APPROVED_BY VARCHAR(100),
    APPROVED_AT TIMESTAMP_NTZ,
    EXECUTION_STATUS VARCHAR(50),
    RESOLUTION_OUTCOME TEXT,
    RESOLUTION_MINUTES INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    AUDIT_TRAIL_JSON VARIANT
);

-- 8. HISTORICAL CASES (Institutional Memory)
CREATE OR REPLACE TABLE HISTORICAL_CASES (
    HISTORICAL_CASE_ID VARCHAR(50) PRIMARY KEY,
    ORIGINAL_TRADE_ID VARCHAR(50),
    CASE_DATE DATE NOT NULL,
    CP_ID VARCHAR(50) REFERENCES COUNTERPARTIES(CP_ID),
    ROOT_CAUSE TEXT NOT NULL,
    APPLIED_PROCEDURE VARCHAR(255) NOT NULL,
    RESOLUTION_STRATEGY TEXT NOT NULL,
    TIME_TO_RESOLVE_HOURS FLOAT NOT NULL,
    OUTCOME VARCHAR(50) NOT NULL,
    CSDR_PENALTY_AVOIDED NUMBER(18, 2) DEFAULT 0.0,
    SIMILARITY_EMBEDDING VECTOR(FLOAT, 768)
);

-- 9. POLICY CHUNKS (SOP Knowledge Base)
CREATE OR REPLACE TABLE POLICY_CHUNKS (
    CHUNK_ID VARCHAR(50) PRIMARY KEY,
    DOC_CODE VARCHAR(50),
    POLICY_NAME VARCHAR(200),
    POLICY_SECTION VARCHAR(100),
    CHUNK_TEXT VARCHAR(5000),
    KEYWORDS ARRAY,
    APPLICABLE_CP_ID VARCHAR(20),
    APPLICABLE_ASSET_CLASS VARCHAR(50),
    RISK_SCORE_IMPACT INTEGER,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

