-- ============================================================================
-- CLEARSET AI — CORTEX ANALYST SEMANTIC VIEWS & VERIFIED QUERIES
-- ============================================================================

USE DATABASE CLEARSET_DB;
USE SCHEMA CLEARSET_SCHEMA;

-- 1. ANALYTICAL VIEW FOR CORTEX AGENT
CREATE OR REPLACE VIEW V_EXCEPTIONS_ENRICHED AS
SELECT 
    e.EXCEPTION_ID,
    e.TRADE_ID,
    e.SEVERITY,
    e.STATUS AS EXCEPTION_STATUS,
    e.EXCEPTION_TYPE,
    e.RISK_SCORE,
    t.TRADE_VALUE,
    t.CURRENCY,
    t.SETTLEMENT_DATE,
    t.SETTLEMENT_TYPE,
    t.CUTOFF_TIME,
    DATEDIFF('minute', CURRENT_TIMESTAMP(), t.CUTOFF_TIME) AS MINUTES_TO_CUTOFF,
    s.TICKER,
    s.NAME AS SECURITY_NAME,
    s.ASSET_CLASS,
    s.DEPOSITORY,
    c.CP_ID,
    c.NAME AS COUNTERPARTY_NAME,
    c.CREDIT_RATING,
    c.PRIOR_FAILURES_30D,
    c.HISTORICAL_FAIL_RATE,
    ssi.STATUS AS SSI_STATUS,
    ssi.CUSTODIAN_BIC
FROM EXCEPTIONS e
JOIN TRADES t ON e.TRADE_ID = t.TRADE_ID
JOIN SECURITIES s ON t.ISIN = s.ISIN
JOIN COUNTERPARTIES c ON t.CP_ID = c.CP_ID
LEFT JOIN SETTLEMENT_INSTRUCTIONS ssi ON t.TRADE_ID = ssi.TRADE_ID;

-- 2. VERIFIED QUERY 1: Critical exceptions approaching cutoff
-- Question: "Show me critical settlement exceptions approaching cutoff."
CREATE OR REPLACE VIEW V_CRITICAL_APPROACHING_CUTOFF AS
SELECT 
    TRADE_ID, 
    TICKER, 
    COUNTERPARTY_NAME, 
    TRADE_VALUE, 
    MINUTES_TO_CUTOFF, 
    RISK_SCORE 
FROM V_EXCEPTIONS_ENRICHED
WHERE SEVERITY = 'CRITICAL' AND EXCEPTION_STATUS IN ('OPEN', 'INVESTIGATING')
ORDER BY RISK_SCORE DESC, MINUTES_TO_CUTOFF ASC;

-- 3. VERIFIED QUERY 2: Counterparty Failure Rate
-- Question: "How many settlement failures has CP-192 had?"
CREATE OR REPLACE VIEW V_COUNTERPARTY_FAIL_STATS AS
SELECT 
    CP_ID, 
    NAME, 
    PRIOR_FAILURES_30D, 
    HISTORICAL_FAIL_RATE, 
    AVG_RESOLUTION_HOURS 
FROM COUNTERPARTIES;
