import React, { useEffect, useState } from 'react';
import { Brain, Zap, AlertCircle, Eye, Shield, CheckCircle2, FileSignature, X } from 'lucide-react';
import { useFeatureFlag } from '../hooks/useFeatureFlag';
import { fetchPredictions } from '../services/apiClient';
import type {
  PredictionItem,
  PredictionModelMetrics,
  PredictionRiskLevel,
} from '../services/types';
import { PanelHeader, ProvenanceTag, SkeletonCard, EmptyState } from './ui/primitives';

const RISK_COLORS: Record<PredictionRiskLevel, string> = {
  CRITICAL: '#FF3B5C',
  HIGH: '#F59E0B',
  MEDIUM: '#3B82F6',
  LOW: '#10B981',
};

const PRIORITY_COLORS: Record<string, string> = {
  IMMEDIATE: '#FF3B5C',
  HIGH: '#F59E0B',
  MEDIUM: '#3B82F6',
  LOW: '#10B981',
};

const formatUsd = (value: number): string => {
  if (!Number.isFinite(value)) return '$0';
  if (Math.abs(value) >= 1_000_000) return `$${(value / 1_000_000).toFixed(2)}M`;
  if (Math.abs(value) >= 1_000) return `$${(value / 1_000).toFixed(1)}K`;
  return `$${value.toFixed(2)}`;
};

const formatPct = (value: number): string => `${(value * 100).toFixed(1)}%`;

/**
 * Builds a SWIFT MT599 free-format prevention request draft.
 * DRAFT ONLY — nothing is transmitted; execution always needs human approval.
 */
const buildMt599Draft = (pred: PredictionItem): string => {
  const amount = (pred.tradeValue ?? 0).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  const topDriver = pred.riskDrivers[0]?.factor ?? 'Settlement risk';
  const topAction = pred.recommendedActions[0]?.action ?? 'Review settlement instruction';
  const reason = pred.riskDrivers[0]?.description ?? '';
  const today = new Date().toISOString().slice(0, 10).replace(/-/g, '');

  return [
    'SWIFT MT599 (FREE FORMAT) — PREVENTION REQUEST',
    '---------------------------------------------',
    `:20: CLEARSET-PREV-${pred.tradeId}`,
    `:21: ${pred.tradeId}`,
    `:32A: ${today} USD${amount}`,
    `:79: TRADE ${pred.tradeId} / CP ${pred.cpId ?? 'N/A'} / ${pred.instructionStatus ?? 'N/A'}`,
    `      RISK ${pred.riskLevel} AT ${(pred.failureProbability * 100).toFixed(1)}%`,
    `      PRIMARY DRIVER: ${topDriver}${reason ? ` — ${reason}` : ''}`,
    `      REQUESTED ACTION: ${topAction}`,
    '      REF: SETTLEMENT EXCEPTION SOP 3.2 (EXPEDITED SSI REPAIR)',
    '      CUTOFF BREACH AVOIDANCE PER CSDR / FCA 52D RULES.',
    '',
    'DRAFT GENERATED BY CLEARSET AI — NOT TRANSMITTED.',
    'RELEASE ONLY AFTER NAMED HUMAN APPROVAL (SOP 2.1).',
  ].join('\n');
};

/**
 * Predictive Settlement Failure Prevention panel (feature-flagged).
 * Renders nothing unless VITE_PREDICTIVE_ENGINE=true, and self-fetches
 * GET /api/predict so the main data flow stays untouched.
 */
export const PredictionPanel: React.FC = () => {
  const enabled = useFeatureFlag('PREDICTIVE_ENGINE');
  const [predictions, setPredictions] = useState<PredictionItem[]>([]);
  const [modelMetrics, setModelMetrics] = useState<PredictionModelMetrics | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'unavailable'>('loading');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [draftId, setDraftId] = useState<string | null>(null);

  useEffect(() => {
    if (!enabled) return undefined;
    let cancelled = false;

    const load = () => {
      fetchPredictions()
        .then((res) => {
          if (cancelled) return;
          if (res.success && res.data) {
            setPredictions(res.data);
            setModelMetrics(res.modelMetrics ?? null);
            setState('ready');
          } else {
            setState('unavailable');
          }
        })
        .catch(() => {
          if (!cancelled) setState('unavailable');
        });
    };

    load();
    const interval = setInterval(load, 60000);
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [enabled]);

  if (!enabled) return null;

  if (state === 'loading') {
    return (
      <div className="bg-[#0F172A] border border-slate-700/80 p-4 rounded-2xl space-y-3 shadow-md">
        <PanelHeader title="Predictive Failure Prevention" meta={<ProvenanceTag kind="computed" />} />
        <SkeletonCard className="h-[240px]" />
      </div>
    );
  }

  if (state === 'unavailable') {
    return (
      <div className="bg-[#0F172A] border border-slate-700/80 p-4 rounded-2xl space-y-3 shadow-md">
        <PanelHeader title="Predictive Failure Prevention" meta={<ProvenanceTag kind="unavailable" />} />
        <EmptyState message="Predictions require the backend flag PREDICTIVE_ENGINE_ENABLED=true." compact />
      </div>
    );
  }

  const critical = predictions.filter((p) => p.riskLevel === 'CRITICAL').length;
  const high = predictions.filter((p) => p.riskLevel === 'HIGH').length;
  const exposure = predictions.reduce((sum, p) => sum + (p.tradeValue ?? 0), 0);
  const dailyPenalty = predictions.reduce((sum, p) => sum + (p.csdrDailyExposure ?? 0), 0);

  return (
    <div className="bg-[#0F172A] border border-slate-700/80 p-4 rounded-2xl space-y-3 shadow-md">
      <PanelHeader
        title="Predictive Failure Prevention"
        badge={
          <span className="text-[9px] font-mono font-semibold px-1.5 py-0.5 rounded border border-emerald-500/30 bg-emerald-500/10 text-emerald-300">
            <Brain className="w-3 h-3 inline-block mr-1" />
            ML MODEL
          </span>
        }
        meta={<ProvenanceTag kind="computed" />}
      />

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div className="bg-[#162032] border border-rose-500/30 p-3 rounded-xl">
          <div className="text-slate-400 text-[10px] font-mono">CRITICAL RISK</div>
          <div className="text-rose-400 font-bold text-lg">{critical}</div>
        </div>
        <div className="bg-[#162032] border border-amber-500/30 p-3 rounded-xl">
          <div className="text-slate-400 text-[10px] font-mono">HIGH RISK</div>
          <div className="text-amber-400 font-bold text-lg">{high}</div>
        </div>
        <div className="bg-[#162032] border border-cyan-500/30 p-3 rounded-xl">
          <div className="text-slate-400 text-[10px] font-mono">NOTIONAL AT RISK</div>
          <div className="text-cyan-400 font-bold text-lg">{formatUsd(exposure)}</div>
        </div>
        <div className="bg-[#162032] border border-emerald-500/30 p-3 rounded-xl">
          <div className="text-slate-400 text-[10px] font-mono">CSDR RISK / DAY</div>
          <div className="text-emerald-400 font-bold text-lg">{formatUsd(dailyPenalty)}</div>
        </div>
      </div>

      <div className="space-y-2 max-h-[420px] overflow-y-auto pr-1">
        {predictions.length === 0 ? (
          <EmptyState message="No trades available for prediction." compact />
        ) : (
          predictions.map((pred) => {
            const color = RISK_COLORS[pred.riskLevel] ?? '#64748B';
            const expanded = expandedId === pred.tradeId;
            return (
              <div
                key={pred.tradeId}
                className={`p-3 rounded-xl border cursor-pointer transition-colors ${
                  expanded
                    ? 'bg-[#181324] border-rose-500/50'
                    : 'bg-[#162032] border-slate-700/50 hover:border-rose-500/30'
                }`}
                onClick={() => setExpandedId(expanded ? null : pred.tradeId)}
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-2">
                  <div className="flex items-center gap-3 min-w-0">
                    <span
                      className="w-2.5 h-2.5 rounded-full shrink-0"
                      style={{ backgroundColor: color }}
                    />
                    <div className="min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-mono font-bold text-white text-xs">{pred.tradeId}</span>
                        <span
                          className="text-[10px] font-mono font-bold px-1.5 py-0.5 rounded border"
                          style={{
                            color,
                            backgroundColor: `${color}1F`,
                            borderColor: `${color}55`,
                          }}
                        >
                          {pred.riskLevel}
                        </span>
                        <span className="text-[10px] font-mono font-bold text-emerald-400">
                          {formatPct(pred.failureProbability)} fail
                        </span>
                      </div>
                      <div className="text-[11px] text-slate-400 mt-1 truncate">
                        {pred.tradeValue !== undefined ? `${formatUsd(pred.tradeValue)} · ` : ''}
                        {pred.instructionStatus ?? '—'} · cutoff in {pred.daysToCutoff ?? '—'}d
                        {pred.csdrDailyExposure ? ` · ${formatUsd(pred.csdrDailyExposure)}/day` : ''}
                      </div>
                    </div>
                  </div>
                  <Zap className="w-4 h-4 text-emerald-400 shrink-0" />
                </div>

                {expanded && (
                  <div className="mt-3 pt-3 border-t border-slate-700/50 grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <AlertCircle className="w-4 h-4 text-rose-400" />
                        <span className="text-xs font-mono font-bold text-slate-300">RISK DRIVERS</span>
                      </div>
                      <div className="space-y-1.5">
                        {pred.riskDrivers.map((driver) => (
                          <div key={driver.factor} className="ml-6 pl-2 border-l border-slate-700/60">
                            <div className="flex items-center justify-between text-[11px] gap-2">
                              <span className="text-slate-300">{driver.factor}</span>
                              <span className="text-[10px] font-mono font-bold text-rose-400 shrink-0">
                                {(driver.impact * 100).toFixed(1)}%
                              </span>
                            </div>
                            <div className="text-[9px] text-slate-500">{driver.description}</div>
                            <div className="text-[9px] text-slate-400">
                              current {driver.currentValue} · threshold {driver.threshold}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                        <span className="text-xs font-mono font-bold text-slate-300">
                          RECOMMENDED ACTIONS
                        </span>
                      </div>
                      <div className="space-y-1.5">
                        {pred.recommendedActions.map((action) => (
                          <div key={action.action} className="ml-6 pl-2 border-l border-slate-700/60">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span
                                className="text-[10px] font-mono font-bold px-1.5 py-0.5 rounded border"
                                style={{
                                  color: PRIORITY_COLORS[action.priority] ?? '#94A3B8',
                                  backgroundColor: `${PRIORITY_COLORS[action.priority] ?? '#94A3B8'}1F`,
                                  borderColor: `${PRIORITY_COLORS[action.priority] ?? '#94A3B8'}55`,
                                }}
                              >
                                {action.priority}
                              </span>
                              <span
                                className={`text-[9px] font-mono font-bold px-1.5 py-0.5 rounded border ${
                                  action.automated
                                    ? 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30'
                                    : 'text-amber-400 bg-amber-500/10 border-amber-500/30'
                                }`}
                              >
                                {action.automated ? 'AUTOMATED' : 'HUMAN'}
                              </span>
                            </div>
                            <div className="text-[11px] text-slate-300 mt-0.5">{action.action}</div>
                            <div className="text-[9px] text-slate-500">{action.description}</div>
                            <div className="text-[9px] text-emerald-400">
                              impact: {action.estimatedImpact}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="md:col-span-2 space-y-2">
                      <div className="flex items-center gap-2 flex-wrap">
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            setDraftId(draftId === pred.tradeId ? null : pred.tradeId);
                          }}
                          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-cyan-700 hover:bg-cyan-600 text-white text-[11px] font-bold transition-colors"
                        >
                          <FileSignature className="w-3.5 h-3.5" />
                          {draftId === pred.tradeId ? 'Hide MT599 draft' : 'Draft prevention MT599'}
                        </button>
                        <span className="text-[9px] font-mono text-slate-500">
                          PREVIEW ONLY — NOTHING IS TRANSMITTED WITHOUT NAMED HUMAN APPROVAL
                        </span>
                      </div>

                      {draftId === pred.tradeId && (
                        <div className="rounded-lg border border-amber-500/40 bg-amber-500/5 p-3">
                          <div className="flex items-center justify-between gap-2 mb-2">
                            <span className="text-[10px] font-mono font-bold text-amber-300">
                              <AlertCircle className="w-3 h-3 inline-block mr-1" />
                              DRAFT — AWAITING HUMAN APPROVAL (SOP 2.1)
                            </span>
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                setDraftId(null);
                              }}
                              className="text-amber-300 hover:text-amber-100"
                              aria-label="Close draft"
                            >
                              <X className="w-3.5 h-3.5" />
                            </button>
                          </div>
                          <pre className="text-[10px] font-mono text-slate-200 whitespace-pre-wrap leading-relaxed">
                            {buildMt599Draft(pred)}
                          </pre>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {modelMetrics && (
        <div className="pt-3 mt-1 border-t border-slate-700/50 flex flex-wrap items-center gap-x-3 gap-y-1 text-[10px] text-slate-500">
          <span className="flex items-center gap-1">
            <Eye className="w-3 h-3" />
            MODEL PERFORMANCE
          </span>
          <span>
            accuracy <span className="text-emerald-400 font-mono">{(modelMetrics.accuracy * 100).toFixed(0)}%</span>
          </span>
          <span>
            f1 <span className="text-cyan-400 font-mono">{(modelMetrics.f1Score * 100).toFixed(0)}%</span>
          </span>
          <span>
            trained <span className="text-slate-300 font-mono">{modelMetrics.trainedOn}</span>
          </span>
          <span>
            samples <span className="text-slate-300 font-mono">{modelMetrics.sampleSize.toLocaleString()}</span>
          </span>
          <span className="flex items-center gap-1">
            <Shield className="w-3 h-3" />
            DECISION SUPPORT ONLY — HUMAN APPROVAL REQUIRED FOR ANY ACTION
          </span>
        </div>
      )}
    </div>
  );
};

export default PredictionPanel;
